Desktop-version-portfolio-pull-request
UsamaMasood12/Portfolio-finish-mobile-version pull request #3
Opened 2022-12-08 12:24 UTC by UsamaMasood12

In this project, I completed the desktop version of the portfolio. I used the mobile-first approach i.e. first I made a mobile version then by alteration and addition of codes, I made a desktop version.

2022-12-08 13:38 UTC, Ugboaja-Uchechi requested changes
Hi @UsamaMasood12, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] According to the Figma design there isn't a See project `button` unless when hovered upon. Kindly fix this 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206456192-838af387-4fbc-4939-b19c-faf97e878a74.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206456244-14181cf4-7f1b-47da-95d9-dba176c9d428.png)

- [ ] When one of the cards are hovered on in  your project section your design should look like this ⬇️. Kindly fix this 🙏 

![image](https://user-images.githubusercontent.com/74814780/206456681-f7e436ba-ad46-4954-956f-58ecc672cc92.png)

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on style.css
>  ul.points {
- [ ] kindly make sure the list of languages and skills e.t.c are aligned properly as seen in the Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/206457799-45d5eaef-e42e-4d80-b6e9-730f28bffbe1.png)  |  ![image](https://user-images.githubusercontent.com/74814780/206457863-c58b18ec-9fd1-45ea-81ce-ef4286d87296.png)

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on style.css
>    margin-left: -8px;
- [ ] Kindly make sure the content of your design fills the browser viewports width so as to make your design look better and more professional 🙏 

![image](https://user-images.githubusercontent.com/74814780/206458570-65e7e63a-a2be-4424-95e0-d9e22bb0734a.png)

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] Your design isn't responsive on all desktop screens. Kindly fix this to make it responsive on all desktop screens 🙏 

![image](https://user-images.githubusercontent.com/74814780/206458992-50cab00b-09e4-4c7d-904b-27e0578a3346.png)

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on index.html
> +                        <div class="profession"><h2>I'am a Software Developer</h2></div>
- [ ] Great job 👍 You gave this text a `font-family` of `Roboto` instead of `Inter`. Kindly fix this 🙏

2022-12-08 13:38 UTC, Ugboaja-Uchechi commented on index.html
> +                                </article>
- [ ] Great job 👍 You gave this text a `font-family` of `Poppins` instead of `Inter`. Kindly fix this 🙏

2022-12-09 12:08 UTC, rskinnerc requested changes
Hi @UsamaMasood12 👋👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/26911718/206699251-738b580b-ef44-4a21-88bd-c3169c7e208a.gif)


 ## Highlights
- You have configured the linters correctly and they are passing ✅
- You are using GitHub Flow correctly
- Good job implementing the hover effect to the project cards 😜😜

 ## Required Changes ♻️
_Check the comments under the review._

Good job implementing some of the required changes. Please check my comments below though. There are still some changes you need to work on. You did a good job starting with the mobile-first approach. From there, once the viewport hits the required `min-width`, it should fit correctly up to the widest resolution (think about how to make the width fluid inside the media query). Kindly, review my required changes as well as double-check the previous ones. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 12:08 UTC, rskinnerc commented on style.css
> +  .body1 {
♻️ Great job using media queries as required!! However, please note that once the viewport width hits the min-width of 768px, the design totally breaks. There is a lot of white space to the right and most of the content is being pushed to the left.

The following screenshot was taken in a 768px width viewport. Please note how there are elements pushed to the left and the content remains to the right. Also not the bottom scrollbar, it should become responsive. That is, the width should fit the full viewport width so it doesn't break or requires the user to scroll horizontally.

![image](https://user-images.githubusercontent.com/26911718/206696583-4a2171e2-bc55-4e96-8560-3699f048d2e5.png)


- [ ] Please make sure that the design fits responsively in all screen sizes. hat would make your design more professional.

This is also happening on some mobile devices. You can check on your mobile the live version [Here](https://raw.githack.com/UsamaMasood12/Portfolio-finish-mobile-version/Desktop-Version/index.html)

2022-12-09 12:08 UTC, rskinnerc commented on style.css
> +    flex-direction: row-reverse;
[OPTIONAL] ⭐ This is an optional recommendation. Please consider using more meaningful names in your classes. That would make your work more professional, readable, and easy to maintain. Whenever you have time, kindly take a look at this short article. That could be a good option [CSS Classes naming conventions](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)

2022-12-09 12:08 UTC, rskinnerc commented on index.html
> +                            <div class="container4">
[OPTIONAL] ⭐ This is an optional change but recommended. I strongly suggest that you keep your code as simplest as possible. Wrapping other elements like `h1` or `p` tags just for styling into a `div` is not recommended. This makes your code less readable, not very semantic and it is not screen-reader friendly. Remember that you always can style those tags directly.

Please also remember that thee `h`1` tag is the most important title on your page. You should avoid using several of these.

2022-12-09 13:52 UTC, DuaneDave commented on index.html
> +                                    <li class="item6">Ruby</li>
[OPTIONAL]  I suggest that you fix how the grid behaves from `768px` to ensure a consistent design on all breakpoints.
[see here](https://duanedave.github.io/Portfolio-Website/) play with the responsiveness and see.

2022-12-09 13:53 UTC, DuaneDave requested changes
Hi @UsamaMasood12 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✅ Great UI 👍 
✅ Meaningful commit history 👍 


 ## Required Changes ♻️
- As requested by the previous reviewers, kindly implement this section at least to look like the figma design. Currently the illustration is not fitting properly from `768px` break point.
     
     -TIP : From my observation i noticed that the text size is not responsive and also the space between the social media icons and text should be adjusted. Finally play a little with the width and height of the illustration

Your design 👇👇👇

<img width="650" alt="badddddddd" src="https://user-images.githubusercontent.com/84930355/206715783-64288c80-c775-48aa-8f92-895906f45256.png">


Figma design 👇👇👇

<img width="412" alt="gooooood" src="https://user-images.githubusercontent.com/84930355/206716395-ab83edef-183a-4fdf-854c-e8a6dd1f3d51.png">
  

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 09:19 UTC, amejid approved these changes
Hi @UsamaMasood12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Nice UI design :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 09:21 UTC, merged