Addition-of-mobile-menu-pull-request
UsamaMasood12/Portfolio-finish-mobile-version pull request #4
Opened 2022-12-19 13:12 UTC by UsamaMasood12

In this project, I added the mobile menu of my portfolio, which only works for mobile screens with help of js code.

2022-12-19 13:39 UTC, Davidosky007 requested changes
Hi @UsamaMasood12 @zewdu444 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Good looking readme file 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-19 13:39 UTC, Davidosky007 commented on style.css
> +}
* Kindly ensure that your menu drop-down fits and is responsive as it currently has a horizontal scroll which gives it not so good user experience below is a recording of the issue 

https://user-images.githubusercontent.com/52497246/208438086-8d298f91-dfef-4493-8d7f-9cc5b0f22f45.mp4

2022-12-19 14:48 UTC, m05e5 requested changes
Hi @UsamaMasood12

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] The horizontal scroll actually scrolls the popup's header up which is not very professional. As mentioned by the previous reviewer, kindly make the popup header fixed like the body

**current design**
<img width="328" alt="image" src="https://user-images.githubusercontent.com/37901469/208451944-b2ce57ad-5265-4768-b41c-75bc014c4a1c.png">
 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-19 20:27 UTC, merged

2022-12-20 07:25 UTC, cindykandie reviewed
Good work

2022-12-20 07:25 UTC, cindykandie commented on style.css
>    width: 190px;
Kindly avoid using fixed widths to have more responsiveness, try using rem/em values

2022-12-20 07:29 UTC, batoorsohail commented
# Highlights:
- No Linters error 👍 
- Well-written PR description 💯 
- Clean Code 🥇

2022-12-20 07:29 UTC, dieum512 commented
I really appreciate this work a lot, but it can be a lot better if you ad the live demo link to your README file to help people see the way your deployed webpage is